# Generated by Django 4.1.3 on 2023-07-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0004_customer_address_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
